version: '3.1'

x-spark-commom:
  &x-spark-commom
  image: docker.io/bitnami/spark:3.3
  volumes:
    - ./:/jupyter:Z
  env_file:
    - .env
  networks:
    - spark

services:
  conda:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: jupyter notebook --allow-root --ip 0.0.0.0
    ports:
      - 8888:8888
    volumes:
      - ./:/jupyter:Z
    working_dir: /jupyter
    tty: true

  spark:
    <<: *x-spark-commom
    ports:
      - '8080:8080'
      - '7077:7077'
    environment:
      - SPARK_MODE=master

  spark-worker:
    <<: *x-spark-commom
    environment:
      - SPARK_MODE=worker

networks:
  spark:
    driver: bridge

