version: '3.1'

services:
  conda:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: jupyter notebook --allow-root --ip 0.0.0.0
    ports:
      - 8888:8888
    volumes:
      - ./:/jupyter:Z
    working_dir: /jupyter
    tty: true
