version: '3.1'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile_python_jupyter
    command: /bin/sh "jupyterlab.sh"
    ports:
      - "8888:8888"
    volumes:
      - ./:/jupyter
    working_dir: /jupyter
    tty: true
