version: '3.1'

services:
  jupyter:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: /bin/sh "/jupyter/docker/dev/jupyterlab.sh"
    ports:
      - "8888:8888"
    volumes:
      - ./:/jupyter:Z
    working_dir: /jupyter
    tty: true
