version: '3.1'

services:
  jupyter:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    command: /bin/sh "/jupyter/docker/prod/jupyterlab.sh"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./:/jupyter:Z
    working_dir: /jupyter
    env_file:
      - .env
    restart: always
